/*
 * Copyright (c) 2025-2026, Sjofn LLC.
 * All rights reserved.
 *
 * - Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * - Neither the name of the openmetaverse.co nor the names
 *   of its contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SkeletonGenerator
{
    [Generator]
    public class SkeletonGenerator : IIncrementalGenerator
    {
        private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        private static readonly DiagnosticDescriptor MissingXml = new(
            "SKG001",
            "Missing avatar_skeleton.xml",
            "AdditionalFile 'avatar_skeleton.xml' not found. Generator will not produce LindenSkeletonDefault.g.cs.",
            "SkeletonGenerator",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor GenerationFailed = new(
            "SKG999",
            "Generation failed",
            "Skeleton generation failed: {0}",
            "SkeletonGenerator",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var xmlProvider = context.AdditionalTextsProvider
                .Where(at => Path.GetFileName(at.Path).Equals("avatar_skeleton.xml", StringComparison.OrdinalIgnoreCase))
                .Select((at, ct) => at.GetText(ct)?.ToString() ?? string.Empty)
                .Collect();

            context.RegisterSourceOutput(xmlProvider, (spc, xmls) =>
            {
                var xmlText = xmls.Length > 0 ? xmls[0] : null;
                if (string.IsNullOrWhiteSpace(xmlText))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(MissingXml, Location.None));
                    return;
                }

                try
                {
                    var generated = Generate(xmlText!);
                    spc.AddSource("LindenSkeletonDefault.g.cs", SourceText.From(generated, Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(GenerationFailed, Location.None, ex.Message));
                }
            });
        }

        private static string Generate(string xmlText)
        {
            var doc = new XmlDocument();
            doc.LoadXml(xmlText);
            var root = doc.DocumentElement!;

            float.TryParse(root.GetAttribute("version"), NumberStyles.Float, Inv, out var version);
            var numBones = root.GetAttribute("num_bones");
            var numCvs = root.GetAttribute("num_collision_volumes");

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace LibreMetaverse.Rendering");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class LindenSkeleton");
            sb.AppendLine("    {");
            sb.AppendLine("        public static LindenSkeleton GetDefault()");
            sb.AppendLine("        {");

            var varNames = new Dictionary<XmlNode, string>();
            int jointIdx = 0, cvIdx = 0;

            XmlElement? rootBone = null;
            foreach (XmlNode child in root.ChildNodes)
            {
                if (child is XmlElement el && el.Name == "bone")
                {
                    rootBone = el;
                    break;
                }
            }

            string rootVarName = "new Joint()";
            if (rootBone != null)
            {
                EmitPostOrder(rootBone, ref jointIdx, ref cvIdx, varNames, sb);
                rootVarName = varNames[rootBone];
            }

            sb.AppendLine("            return new LindenSkeleton");
            sb.AppendLine("            {");
            sb.AppendLine($"                version = {FormatFloat(version)},");
            sb.AppendLine($"                num_bones = \"{numBones}\",");
            sb.AppendLine($"                num_collision_volumes = \"{numCvs}\",");
            sb.AppendLine($"                bone = {rootVarName}");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static void EmitPostOrder(XmlElement node, ref int jointIdx, ref int cvIdx,
            Dictionary<XmlNode, string> varNames, StringBuilder sb)
        {
            var childCvs = new List<XmlElement>();
            var childBones = new List<XmlElement>();
            foreach (XmlNode child in node.ChildNodes)
            {
                if (child is not XmlElement el) continue;
                if (el.Name == "collision_volume") childCvs.Add(el);
                else if (el.Name == "bone") childBones.Add(el);
            }

            foreach (var cv in childCvs)
            {
                var cvName = $"_cv{cvIdx++}";
                varNames[cv] = cvName;
                sb.Append($"            var {cvName} = new CollisionVolume {{ ");
                AppendJointBaseFields(cv, sb);
                sb.AppendLine("};");
            }

            foreach (var childBone in childBones)
                EmitPostOrder(childBone, ref jointIdx, ref cvIdx, varNames, sb);

            var varName = $"_j{jointIdx++}";
            varNames[node] = varName;

            sb.Append($"            var {varName} = new Joint {{ ");
            AppendJointBaseFields(node, sb);

            var pivot = ParseFloats(node.GetAttribute("pivot"));
            if (pivot != null)
            {
                sb.Append("pivot = new float[] { ");
                AppendFloats(pivot, sb);
                sb.Append(" }, ");
            }

            var aliases = node.GetAttribute("aliases");
            if (!string.IsNullOrEmpty(aliases))
                sb.Append($"aliases = \"{aliases}\", ");

            if (node.GetAttribute("connected").Equals("true", StringComparison.OrdinalIgnoreCase))
                sb.Append("connected = true, ");

            if (childCvs.Count > 0)
            {
                sb.Append("collision_volume = new CollisionVolume[] { ");
                for (int i = 0; i < childCvs.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(varNames[childCvs[i]]);
                }
                sb.Append(" }, ");
            }

            if (childBones.Count > 0)
            {
                sb.Append("bone = new Joint[] { ");
                for (int i = 0; i < childBones.Count; i++)
                {
                    if (i > 0) sb.Append(", ");
                    sb.Append(varNames[childBones[i]]);
                }
                sb.Append(" }, ");
            }

            sb.AppendLine("};");
        }

        private static void AppendJointBaseFields(XmlElement node, StringBuilder sb)
        {
            sb.Append($"name = \"{node.GetAttribute("name")}\", ");

            var pos = ParseFloats(node.GetAttribute("pos"));
            if (pos != null) { sb.Append("pos = new float[] { "); AppendFloats(pos, sb); sb.Append(" }, "); }

            var rot = ParseFloats(node.GetAttribute("rot"));
            if (rot != null) { sb.Append("rot = new float[] { "); AppendFloats(rot, sb); sb.Append(" }, "); }

            var scale = ParseFloats(node.GetAttribute("scale"));
            if (scale != null) { sb.Append("scale = new float[] { "); AppendFloats(scale, sb); sb.Append(" }, "); }

            var group = node.GetAttribute("group");
            if (!string.IsNullOrEmpty(group)) sb.Append($"group = \"{group}\", ");

            var support = node.GetAttribute("support");
            if (!string.IsNullOrEmpty(support)) sb.Append($"support = \"{support}\", ");

            var end = ParseFloats(node.GetAttribute("end"));
            if (end != null) { sb.Append("end = new float[] { "); AppendFloats(end, sb); sb.Append(" }, "); }

            if (node.GetAttribute("reposition").Equals("true", StringComparison.OrdinalIgnoreCase))
                sb.Append("reposition = true, ");
        }

        private static void AppendFloats(float[] floats, StringBuilder sb)
        {
            for (int i = 0; i < floats.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(FormatFloat(floats[i]));
            }
        }

        private static float[]? ParseFloats(string value)
        {
            if (string.IsNullOrWhiteSpace(value)) return null;
            var parts = value.Trim().Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);
            var result = new float[parts.Length];
            int count = 0;
            foreach (var p in parts)
            {
                if (float.TryParse(p, NumberStyles.Float, Inv, out var f))
                    result[count++] = f;
            }
            if (count == 0) return null;
            if (count == result.Length) return result;
            var trimmed = new float[count];
            Array.Copy(result, trimmed, count);
            return trimmed;
        }

        private static string FormatFloat(float f)
        {
            if (f == 0f) return "0f";
            return f.ToString("G9", Inv) + "f";
        }
    }
}
