/*
 * Copyright (c) 2025-2026, Sjofn LLC.
 * All rights reserved.
 *
 * - Redistribution and use in source and binary forms, with or without
 *   modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * - Neither the name of the openmetaverse.co nor the names
 *   of its contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

using System;
using System.Globalization;
using System.IO;
using System.Text;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace GenepoolGenerator
{
    [Generator]
    public class GenepoolGenerator : IIncrementalGenerator
    {
        private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

        private static readonly DiagnosticDescriptor MissingXml = new(
            "GPG001",
            "Missing genepool.xml",
            "AdditionalFile 'genepool.xml' not found. Generator will not produce Genepool.g.cs.",
            "GenepoolGenerator",
            DiagnosticSeverity.Warning,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor GenerationFailed = new(
            "GPG999",
            "Generation failed",
            "Genepool generation failed: {0}",
            "GenepoolGenerator",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var xmlProvider = context.AdditionalTextsProvider
                .Where(at => Path.GetFileName(at.Path).Equals("genepool.xml", StringComparison.OrdinalIgnoreCase))
                .Select((at, ct) => at.GetText(ct)?.ToString() ?? string.Empty)
                .Collect();

            context.RegisterSourceOutput(xmlProvider, (spc, xmls) =>
            {
                var xmlText = xmls.Length > 0 ? xmls[0] : null;
                if (string.IsNullOrWhiteSpace(xmlText))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(MissingXml, Location.None));
                    return;
                }

                try
                {
                    var generated = Generate(xmlText!);
                    spc.AddSource("Genepool.g.cs", SourceText.From(generated, Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(GenerationFailed, Location.None, ex.Message));
                }
            });
        }

        private static string Generate(string xmlText)
        {
            var doc = new XmlDocument();
            doc.LoadXml(xmlText);
            var root = doc.DocumentElement!;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace LibreMetaverse");
            sb.AppendLine("{");

            sb.AppendLine("    /// <summary>A single visual parameter value within a genepool archetype.</summary>");
            sb.AppendLine("    public readonly struct ArchetypeParam");
            sb.AppendLine("    {");
            sb.AppendLine("        public int Id { get; init; }");
            sb.AppendLine("        public string Name { get; init; }");
            sb.AppendLine("        public float Value { get; init; }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    /// <summary>A named set of visual parameter values representing an avatar body archetype.</summary>");
            sb.AppendLine("    public readonly struct GenepoolArchetype");
            sb.AppendLine("    {");
            sb.AppendLine("        public string Name { get; init; }");
            sb.AppendLine("        public ArchetypeParam[] Params { get; init; }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    /// <summary>Avatar archetypes from genepool.xml, used to generate randomized avatar appearances.</summary>");
            sb.AppendLine("    public static class Genepool");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly GenepoolArchetype[] Archetypes = new GenepoolArchetype[]");
            sb.AppendLine("        {");

            foreach (XmlNode archNode in root.ChildNodes)
            {
                if (archNode is not XmlElement archEl || archEl.Name != "archetype") continue;

                var archName = Escape(archEl.GetAttribute("name").Trim());
                sb.AppendLine($"            new GenepoolArchetype");
                sb.AppendLine($"            {{");
                sb.AppendLine($"                Name = \"{archName}\",");
                sb.AppendLine($"                Params = new ArchetypeParam[]");
                sb.AppendLine($"                {{");

                foreach (XmlNode paramNode in archEl.ChildNodes)
                {
                    if (paramNode is not XmlElement paramEl || paramEl.Name != "param") continue;

                    var id = paramEl.GetAttribute("id");
                    var name = Escape(paramEl.GetAttribute("name"));
                    var value = ParseFloat(paramEl.GetAttribute("value"));
                    sb.AppendLine($"                    new ArchetypeParam {{ Id = {id}, Name = \"{name}\", Value = {value} }},");
                }

                sb.AppendLine($"                }}");
                sb.AppendLine($"            }},");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Returns the index of the archetype with the given name, or -1 if not found.</summary>");
            sb.AppendLine("        public static int FindIndex(string name)");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = 0; i < Archetypes.Length; i++)");
            sb.AppendLine("                if (Archetypes[i].Name == name) return i;");
            sb.AppendLine("            return -1;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>Returns a reference to the archetype at the given index.</summary>");
            sb.AppendLine("        public static ref readonly GenepoolArchetype Get(int index) => ref Archetypes[index];");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string FormatFloat(float f)
        {
            if (f == 0f) return "0f";
            return f.ToString("G9", Inv) + "f";
        }

        private static string ParseFloat(string s)
        {
            if (float.TryParse(s, NumberStyles.Float, Inv, out var f))
                return FormatFloat(f);
            return "0f";
        }

        private static string Escape(string s) =>
            s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
