/*
 * Copyright (c) 2006-2016, openmetaverse.co
 * Copyright (c) 2025, Sjofn LLC.
 * All rights reserved.
 *
 * - Redistribution and use in source and binary forms, with or without 
 *   modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * - Neither the name of the openmetaverse.co nor the names 
 *   of its contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
 * POSSIBILITY OF SUCH DAMAGE.
 */

using System;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using OpenMetaverse.Packets;
using OpenMetaverse.Interfaces;

namespace OpenMetaverse
{
    /// <summary>
    /// Registers, unregisters, and fires events generated by incoming packets
    /// </summary>
    public class PacketEventDictionary
    {
        private sealed class PacketCallback
        {
            public readonly EventHandler<PacketReceivedEventArgs> Callback;
            public readonly bool IsAsync;

            public PacketCallback(EventHandler<PacketReceivedEventArgs> callback, bool isAsync)
            {
                Callback = callback;
                IsAsync = isAsync;
            }

            public PacketCallback WithAdded(EventHandler<PacketReceivedEventArgs> add, bool isAsync)
            {
                return new PacketCallback(Callback + add, IsAsync || isAsync);
            }

            public PacketCallback WithRemoved(EventHandler<PacketReceivedEventArgs> remove)
            {
                var newCallback = Callback - remove;
                return new PacketCallback(newCallback, IsAsync);
            }
        }

        /// <summary>Reference to the GridClient object</summary>
        public GridClient Client;

        // Use ConcurrentDictionary to avoid locks on the hot read path
        private readonly ConcurrentDictionary<PacketType, PacketCallback> _EventTable =
            new ConcurrentDictionary<PacketType, PacketCallback>();

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="client"></param>
        public PacketEventDictionary(GridClient client)
        {
            Client = client;
        }

        /// <summary>
        /// Register an event handler
        /// </summary>
        /// <remarks>Use PacketType.Default to fire this event on every 
        /// incoming packet</remarks>
        /// <param name="packetType">Packet type to register the handler for</param>
        /// <param name="eventHandler">Callback to be fired</param>
        /// <param name="isAsync">True if this callback should be ran 
        /// asynchronously, false to run it synchronous</param>
        public void RegisterEvent(PacketType packetType, EventHandler<PacketReceivedEventArgs> eventHandler, bool isAsync)
        {
            _EventTable.AddOrUpdate(packetType,
                key => new PacketCallback(eventHandler, isAsync),
                (key, existing) => existing.WithAdded(eventHandler, isAsync));
        }

        /// <summary>
        /// Unregister an event handler
        /// </summary>
        /// <param name="packetType">Packet type to unregister the handler for</param>
        /// <param name="eventHandler">Callback to be unregistered</param>
        public void UnregisterEvent(PacketType packetType, EventHandler<PacketReceivedEventArgs> eventHandler)
        {
            if (_EventTable.TryGetValue(packetType, out var existing))
            {
                var newCallback = existing.Callback - eventHandler;
                if (newCallback == null)
                {
                    // Remove the key entirely if no delegates remain
                    _EventTable.TryRemove(packetType, out _);
                }
                else
                {
                    // Try to update with the reduced delegate (conservative IsAsync kept)
                    _EventTable.TryUpdate(packetType, new PacketCallback(newCallback, existing.IsAsync), existing);
                }
            }
        }

        /// <summary>
        /// Fire the events registered for this packet type
        /// </summary>
        /// <param name="packetType">Incoming packet type</param>
        /// <param name="packet">Incoming packet</param>
        /// <param name="simulator">Simulator this packet was received from</param>
        internal void RaiseEvent(PacketType packetType, Packet packet, Simulator simulator)
        {
            // Default handler first, if one exists
            if (_EventTable.TryGetValue(PacketType.Default, out var callback) && callback.Callback != null)
            {
                if (callback.IsAsync)
                {
                    var cb = callback.Callback;
                    Task.Run(() =>
                    {
                        try { cb(this, new PacketReceivedEventArgs(packet, simulator)); }
                        catch (Exception ex) { Logger.Log("Async Default packet event handler: " + ex, Helpers.LogLevel.Error, Client); }
                    });
                }
                else
                {
                    try { callback.Callback(this, new PacketReceivedEventArgs(packet, simulator)); }
                    catch (Exception ex)
                    {
                        Logger.Log("Default packet event handler: " + ex, Helpers.LogLevel.Error, Client);
                    }
                }
            }

            // Specific packet type handlers
            if (_EventTable.TryGetValue(packetType, out callback) && callback.Callback != null)
            {
                if (callback.IsAsync)
                {
                    var cb = callback.Callback;
                    Task.Run(() =>
                    {
                        try { cb(this, new PacketReceivedEventArgs(packet, simulator)); }
                        catch (Exception ex) { Logger.Log("Async Packet Event Handler: " + ex, Helpers.LogLevel.Error, Client); }
                    });
                }
                else
                {
                    try { callback.Callback(this, new PacketReceivedEventArgs(packet, simulator)); }
                    catch (Exception ex)
                    {
                        Logger.Log("Packet event handler: " + ex, Helpers.LogLevel.Error, Client);
                    }
                }

                return;
            }

            if (packetType != PacketType.Default && packetType != PacketType.PacketAck)
            {
                Logger.DebugLog("No handler registered for packet event " + packetType, Client);
            }
        }
    }

    /// <summary>
    /// Registers, unregisters, and fires events generated by the Capabilities
    /// event queue
    /// </summary>
    public class CapsEventDictionary
    {
        /// <summary>Reference to the GridClient object</summary>
        public GridClient Client;

        private readonly ConcurrentDictionary<string, Caps.EventQueueCallback> _EventTable =
            new ConcurrentDictionary<string, Caps.EventQueueCallback>();

        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="client">Reference to the GridClient object</param>
        public CapsEventDictionary(GridClient client)
        {
            Client = client;
        }

        /// <summary>
        /// Register a new event handler for a capabilities event sent via the EventQueue
        /// </summary>
        /// <remarks>Use String.Empty to fire this event on every CAPS event</remarks>
        /// <param name="capsEvent">Capability event name to register the 
        /// handler for</param>
        /// <param name="eventHandler">Callback to fire</param>
        public void RegisterEvent(string capsEvent, Caps.EventQueueCallback eventHandler)
        {
            _EventTable.AddOrUpdate(capsEvent,
                key => eventHandler,
                (key, existing) => existing + eventHandler);
        }

        /// <summary>
        /// Unregister a previously registered capabilities handler 
        /// </summary>
        /// <param name="capsEvent">Capability event name unregister the 
        /// handler for</param>
        /// <param name="eventHandler">Callback to unregister</param>
        public void UnregisterEvent(string capsEvent, Caps.EventQueueCallback eventHandler)
        {
            if (_EventTable.TryGetValue(capsEvent, out var existing) && existing != null)
            {
                var updated = existing - eventHandler;
                if (updated == null)
                {
                    _EventTable.TryRemove(capsEvent, out _);
                }
                else
                {
                    _EventTable.TryUpdate(capsEvent, updated, existing);
                }
            }
        }

        /// <summary>
        /// Fire the events registered for this event type synchronously
        /// </summary>
        /// <param name="capsEvent">Capability name</param>
        /// <param name="message">Decoded event body</param>
        /// <param name="simulator">Reference to the simulator that 
        /// generated this event</param>
        internal void RaiseEvent(string capsEvent, IMessage message, Simulator simulator)
        {
            bool specialHandler = false;

            // Default handler first (global), if one exists
            if (_EventTable.TryGetValue(string.Empty, out var callback) && callback != null)
            {
                try { callback(capsEvent, message, simulator); }
                catch (Exception ex) { Logger.Log("CAPS Event Handler: " + ex, Helpers.LogLevel.Error, Client); }
            }

            // Explicit handler next
            if (_EventTable.TryGetValue(capsEvent, out callback) && callback != null)
            {
                try { callback(capsEvent, message, simulator); }
                catch (Exception ex) { Logger.Log("CAPS Event Handler: " + ex, Helpers.LogLevel.Error, Client); }

                specialHandler = true;
            }

            if (!specialHandler)
                Logger.Log("Unhandled CAPS event " + capsEvent, Helpers.LogLevel.Warning, Client);
        }

        /// <summary>
        /// Fire the events registered for this event type asynchronously
        /// </summary>
        /// <param name="capsEvent">Capability name</param>
        /// <param name="message">Decoded event body</param>
        /// <param name="simulator">Reference to the simulator that 
        /// generated this event</param>
        internal void BeginRaiseEvent(string capsEvent, IMessage message, Simulator simulator)
        {
            bool specialHandler = false;

            // Default handler first (global), if one exists - run asynchronously
            if (_EventTable.TryGetValue(string.Empty, out var callback) && callback != null)
            {
                var cb = callback;
                Task.Run(() =>
                {
                    try { cb(capsEvent, message, simulator); }
                    catch (Exception ex) { Logger.Log("Async CAPS Event Handler: " + ex, Helpers.LogLevel.Error, Client); }
                });
            }

            // Explicit handler next - run asynchronously
            if (_EventTable.TryGetValue(capsEvent, out callback) && callback != null)
            {
                var cb = callback;
                Task.Run(() =>
                {
                    try { cb(capsEvent, message, simulator); }
                    catch (Exception ex) { Logger.Log("Async CAPS Event Handler: " + ex, Helpers.LogLevel.Error, Client); }
                });

                specialHandler = true;
            }

            if (!specialHandler)
                Logger.Log("Unhandled CAPS event " + capsEvent, Helpers.LogLevel.Warning, Client);
        }
    }
}
